stages:
  - build
  - test

build:
  stage:
    build
  tags:
    - docker-runner
  image:
    rust
  script: "cargo build --all --release"

test:
  stage:
    test
  tags:
    - docker-runner
  image:
    rust
  before_script:
    - |
      VERSION=$(curl https://download.mosek.com/stable/12.0/version)
      curl -L -o mosektoolslinux64x86.tar.bz2 http://download.mosek.com/stable/$VERSION/mosektoolslinux64x86.tar.bz2
      tar xf mosektoolslinux64x86.tar.bz2
  variables:
    LD_LIBRARY_PATH: minidist/bin
  script:
    - |
      cargo test --release
      cargo test --examples --release
      cargo test --doc --release
