stages:
  - build
  - test

build:
  stage:
    build
  tags:
    - docker-runner
  image:
    ubuntu/rust:1.85-24.04_edge
  script: "cargo build --all --release"

test:
  stage:
    test
  tags:
    - docker-runner
  image:
    ubuntu/rust:1.85-24.04_edge
  before_script:
    - |
      curl -o minidist-linux64x86.tar.bz2 http://files.mosek.intranet/artifacts/item/mosek/minidist-linux64x86-12.0
      tar xf minidist-linux64x86.tar.bz2
  script: "LD_LIBRARY_PATH=minidist/bin cargo test --all --release"
